version: "3.8"

services:
  mysqldb:
    container_name: mysql_network
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql_docker
    networks:
      springboot-mysql-net:

  springboot-mysql-docker:
    container_name: springboot-mysql-docker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
